#
# This source file is part of the StanfordBDHG VisionProSurgery project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: VisionProSurgery.xcodeproj
schemes:
- VisionProSurgery
targets:
- VisionProSurgery
- VisionProSurgeryTests
- VisionProSurgeryUITests
- VisionProSurgeryWatchApplication
