#
# This source file is part of the StanfordBDHG VisionProSurgery project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

ignore:
- VisionProSurgeryUITests
- VisionProSurgeryTests
