version = 1

[[annotations]]
path = ["VisionProSurgery.xcodeproj/**", "VisionProSurgery/Assets.xcassets/**", "README_assets/**"]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
